#region

using System;
using System.Reflection;
using System.Runtime.InteropServices;
using System.Security;
using System.Security.Permissions;

#endregion

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: CLSCompliant(true)]
[assembly: ComVisible(false)]
[assembly: AllowPartiallyTrustedCallers]
[assembly: SecurityPermission(SecurityAction.RequestMinimum)]
[assembly: AssemblyCompany("http://springsource.org/spring-gemfire/")]
[assembly: AssemblyCopyright("Copyright 2010 SpringSource.")]
[assembly: AssemblyTrademark("Apache License, Version 2.0")]
[assembly: AssemblyCulture("")]
[assembly: AssemblyVersion("1.0.0.3849")]
[assembly: AssemblyConfiguration("net-3.5.win32; dev")]
[assembly: AssemblyInformationalVersion("1.0.0.3849; net-3.5.win32; dev")]
[assembly: AssemblyDelaySign(false)]