using System;
using System.Reflection;
using System.Runtime.InteropServices;
using System.Security;
using System.Security.Permissions;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5448
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: CLSCompliantAttribute(true)]
[assembly: ComVisibleAttribute(false)]
[assembly: AllowPartiallyTrustedCallersAttribute()]
[assembly: SecurityPermissionAttribute(SecurityAction.RequestMinimum)]
[assembly: AssemblyCompanyAttribute("http://springsource.org/spring-gemfire/")]
[assembly: AssemblyCopyrightAttribute("Copyright 2011 SpringSource.")]
[assembly: AssemblyTrademarkAttribute("Apache License, Version 2.0")]
[assembly: AssemblyCultureAttribute("")]
[assembly: AssemblyVersionAttribute("1.0.2.658")]
[assembly: AssemblyConfigurationAttribute("net-2.0.win32; release")]
[assembly: AssemblyInformationalVersionAttribute("1.0.2.658; net-2.0.win32; release")]
[assembly: AssemblyDelaySignAttribute(false)]

